import { useState } from 'react';
import { AlertCircle, Check, Download, FileCheck2, RefreshCw, Save, ShieldCheck } from 'lucide-react';
import { captureEvidence } from '../appState.js';
import { downloadFile } from '../download.js';
import WorkflowDialog from './WorkflowDialog.jsx';
import './workflow-ui.css';

export default function EvidenceView({ appState, centreId, initialEvidenceId, onSave, onClose, onOpenInfrastructure, onDownload }) {
  const [snapshot, setSnapshot] = useState(() => appState.evidence.find(e => e.id === initialEvidenceId) || captureEvidence(appState, centreId));
  const [note, setNote] = useState(snapshot.reviewNote || '');
  const [error, setError] = useState('');
  const saved = appState.evidence.find(e => e.id === snapshot.id);
  const centre = snapshot.centre;
  const difference = centre.detected === null ? null : centre.detected - centre.claimed;
  const flagged = difference !== null && Math.abs(difference) >= snapshot.threshold;
  const archive = appState.evidence.filter(e => e.centre.id === centreId);
  function refresh() { setSnapshot(captureEvidence(appState, centreId)); setNote(''); setError(''); }
  function save(event) { event.preventDefault(); try { onSave(snapshot, note); setError(''); } catch (failure) { setError(failure.message); } }
  return <WorkflowDialog title="Evidence review" eyebrow={`${centre.id} · count summary, not retained footage`} onClose={onClose} wide>
    <div className="wf-evidence-body"><div className="wf-evidence-top"><div><span className="small-eyebrow">Frozen review snapshot</span><h3>{centre.name}</h3><p>Captured {new Date(snapshot.capturedAt).toLocaleString()} · source revision {snapshot.sourceRevision}</p></div><span className={`wf-pill ${saved ? 'good' : 'warn'}`}>{saved ? <><Check size={13} /> Saved evidence</> : 'Not saved yet'}</span></div>
      <div className="wf-info"><ShieldCheck size={19} /><div><strong>What is evidence here?</strong><p>This is a dated copy of the available counts, source, inventory and review records. It contains no image or video. Use it to document a question—not to prove who attended.</p></div></div>
      <div className="wf-evidence-metrics"><div><span>Submitted register</span><strong>{centre.claimed}</strong></div><div><span>Observed snapshot</span><strong>{centre.detected ?? '—'}</strong></div><div className={flagged ? 'wf-amber' : ''}><span>Observed − submitted</span><strong>{difference === null ? 'Unknown' : difference > 0 ? `+${difference}` : difference}</strong></div><div><span>Review threshold</span><strong>{snapshot.threshold}<small>people</small></strong></div></div>
      <div className="wf-evidence-columns"><section><h3>Source & interpretation</h3><dl className="wf-definition"><div><dt>Count source</dt><dd>{centre.source === 'local-ai' ? 'User-saved COCO-SSD analysis' : centre.source === 'simulation' ? 'Synthetic centre simulation' : 'No connected analysis / manual onboarding'}</dd></div><div><dt>Observation time</dt><dd>{centre.observedAt ? new Date(centre.observedAt).toLocaleString() : 'No observation'}</dd></div><div><dt>Camera connection</dt><dd>{centre.connection} · separate from local file analysis</dd></div><div><dt>Confidence</dt><dd>{centre.source === 'simulation' ? 'Not measured: synthetic counts' : 'Not stored in the saved count summary'}</dd></div><div><dt>Review signal</dt><dd>{difference === null ? 'Unavailable; do not infer absence' : flagged ? 'Difference meets the configured review threshold' : 'Below threshold; not verified attendance'}</dd></div></dl><p className="wf-warning"><AlertCircle size={15} /> Camera 01’s animated tracks are a separate demonstration, not the evidence source for this centre-wide count.</p></section>
      <section><h3>Inventory supporting this snapshot</h3><div className="wf-evidence-table-wrap"><table className="wf-evidence-table"><thead><tr><th>Asset</th><th>Approved</th><th>Visual</th><th>Human verified</th></tr></thead><tbody>{centre.inventory.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.approved}</td><td>{item.detected ?? 'Unknown'}</td><td>{item.verifiedCount ?? 'Not reviewed'}</td></tr>)}</tbody></table></div><button className="text-button" onClick={() => { onClose(); onOpenInfrastructure(centreId); }}>Open inventory review <FileCheck2 size={14} /></button></section></div>
      <section className="wf-evidence-alerts"><h3>Review queue at capture</h3>{snapshot.alerts.length ? snapshot.alerts.map(alert => <article key={alert.id}><span className={`wf-pill ${alert.status === 'resolved' ? 'good' : 'warn'}`}>{alert.status}</span><div><strong>{alert.type}</strong><p>{alert.summary}</p></div></article>) : <p className="wf-description">No review alerts were recorded for this centre at capture.</p>}</section>
      <form onSubmit={save} className="wf-evidence-note"><label className="wf-field">Reviewer note<textarea rows="3" maxLength="2000" required value={saved?.reviewNote || note} readOnly={Boolean(saved)} onChange={event => { setNote(event.target.value); setError(''); }} placeholder="Record context, a question to verify, or the next human-review step…" /><small>{saved ? `Saved locally at ${new Date(saved.savedAt).toLocaleString()} by ${saved.reviewer}.` : 'A note is required to save this evidence snapshot. Saving does not resolve an alert or verify attendance.'}</small></label>{error && <p className="wf-error" role="alert">{error}</p>}<div className="wf-actions"><button className="button button-primary" disabled={Boolean(saved) || !note.trim()} type="submit">{saved ? <Check size={15} /> : <Save size={15} />}{saved ? 'Evidence saved' : 'Save evidence & note'}</button><button className="button button-secondary" type="button" onClick={() => { downloadFile(`${snapshot.id}.json`, JSON.stringify(saved || snapshot, null, 2)); onDownload('Evidence summary downloaded. No footage included.'); }}><Download size={15} /> Download summary</button><button className="button button-secondary" type="button" onClick={refresh}><RefreshCw size={14} /> Capture latest</button></div><p className="wf-description">{appState.dataRevision !== snapshot.sourceRevision ? 'Workspace data changed after capture. This snapshot is preserved; use Capture latest for current values.' : 'This snapshot matches the current workspace revision.'}</p></form>
      {archive.length > 0 && <section className="wf-evidence-archive"><h3>Saved evidence for this centre</h3>{archive.map(item => <button key={item.id} aria-pressed={snapshot.id === item.id} onClick={() => { setSnapshot(item); setNote(item.reviewNote); setError(''); }}><FileCheck2 size={15} /><span>{new Date(item.capturedAt).toLocaleString()}<small>{item.reviewNote}</small></span><Check size={13} /></button>)}</section>}
    </div>
  </WorkflowDialog>;
}
