import { useState } from 'react';
import { AlertCircle, ArrowRight, Building2, Check, ChevronDown, ClipboardCheck, Eye, HardDrive, ScanLine, Save } from 'lucide-react';
import TrackingCamera from './TrackingCamera.jsx';
import './workflow-ui.css';

export default function LiveMonitor({ centre, centres, isLive, settings, history, evidence, onSelect, onSaveRegister, onOpenVision, onOpenEvidence, onOpenInfrastructure }) {
  const entries = history.filter(entry => entry.centreId === centre.id).slice(0, 5);
  const evidenceCount = evidence.filter(item => item.centre.id === centre.id).length;
  return <div className="view-stack"><section className="monitor-toolbar"><div className="centre-selector"><label htmlFor="centre-select">Viewing centre</label><div className="select-wrap"><Building2 size={16} /><select id="centre-select" value={centre.id} onChange={event => onSelect(event.target.value)}>{centres.map(item => <option value={item.id} key={item.id}>{item.name} · {item.city}</option>)}</select><ChevronDown size={15} /></div></div><div className="monitor-toolbar-actions"><span className="stream-health"><span className="status-dot" />{centre.connection === 'online' ? 'Demo connection available' : 'Awaiting connection'}</span><button className="button button-secondary" onClick={onOpenVision}><ScanLine size={15} /> Vision Lab</button><button className="button button-dark" onClick={onOpenEvidence}><Eye size={15} /> Evidence view {evidenceCount > 0 && <span className="wf-button-count">{evidenceCount}</span>}</button></div></section>
    <div className="wf-evidence-prompt"><FileHint /><span><strong>Evidence view</strong> opens a dated count summary, source details and review records. Add a note, save the snapshot, or download it—no retained footage.</span><button className="text-button" onClick={onOpenEvidence}>Review evidence <ArrowRight size={13} /></button></div>
    <section className="monitor-grid"><TrackingCamera centre={centre} isLive={isLive} reducedMotion={settings.reducedMotion} lowResource={settings.lowBandwidth} /><RegisterPanel key={centre.id} centre={centre} threshold={settings.mismatchThreshold} onSave={onSaveRegister} /></section>
    <section className="dashboard-grid dashboard-grid-secondary"><div className="panel signal-panel"><div className="panel-heading"><div><div className="small-eyebrow">Infrastructure glance</div><h2>Approved vs observed</h2></div><button className="text-button" onClick={() => onOpenInfrastructure(centre.id)}>Review inventory <ArrowRight size={14} /></button></div>{centre.inventory.map(item => <button className="inventory-row wf-inventory-link" key={item.id} onClick={() => onOpenInfrastructure(centre.id, item.id)}><span className={`inventory-symbol ${item.detected === null ? 'unavailable' : item.detected < item.approved ? 'gap' : 'ok'}`}><HardDrive size={14} /></span><span className="inventory-name"><strong>{item.name}</strong><small>{item.reviewStatus === 'requested' ? 'verification requested' : item.reviewStatus === 'reviewed' ? 'human review saved' : item.operability}</small></span><span className="inventory-count">{item.detected ?? 'Unknown'} / {item.approved}</span><ArrowRight size={13} /></button>)}</div>
    <div className="panel timeline-panel"><div className="panel-heading"><div><div className="small-eyebrow">Saved local activity</div><h2>Centre review trail</h2></div></div><div className="wf-live-history">{entries.length ? entries.map(entry => <article key={entry.id}><span className="wf-history-dot" /><div><strong>{entry.summary}</strong><small>{new Date(entry.createdAt).toLocaleString()} · {entry.actor}</small></div></article>) : <p>No saved activity for this centre yet. Register changes, evidence notes and inventory reviews will appear here.</p>}</div></div></section>
  </div>;
}
function FileHint() { return <ClipboardCheck size={18} />; }
function RegisterPanel({ centre, threshold, onSave }) {
  const [claimed, setClaimed] = useState(String(centre.claimed));
  const [baseline, setBaseline] = useState(centre.claimed);
  const [saved, setSaved] = useState('');
  const [error, setError] = useState('');
  const value = Number(claimed);
  const valid = claimed.trim() !== '' && Number.isSafeInteger(value) && value >= 0 && value <= centre.capacity;
  const dirty = valid && value !== baseline;
  const difference = centre.detected === null ? null : centre.detected - centre.claimed;
  function submit(event) {
    event.preventDefault();
    try { const result = onSave(centre.id, claimed); setBaseline(result.claimed); setClaimed(String(result.claimed)); setSaved(new Date().toLocaleTimeString()); setError(''); }
    catch (failure) { setError(failure.message); }
  }
  return <div className="panel presence-panel"><div className="panel-heading"><div><div className="small-eyebrow">Centre snapshot · separate from demo</div><h2>Presence reconciliation</h2></div></div><div className="presence-number"><span>{centre.detected ?? '—'}</span><small>{centre.source === 'local-ai' ? 'saved local-analysis count' : centre.detected === null ? 'no available observation' : 'simulated centre-wide presence'}</small></div><div className="comparison-row"><div><span>Saved register</span><strong>{centre.claimed}</strong></div><div className={difference !== null && Math.abs(difference) >= threshold ? 'comparison-alert' : ''}><span>Observed − submitted</span><strong>{difference === null ? '—' : difference > 0 ? `+${difference}` : difference}</strong></div></div><p className="panel-note"><AlertCircle size={14} />{difference === null ? 'No observation is available. Offline does not mean absent.' : Math.abs(difference) >= threshold ? `Difference meets the ${threshold}-person review threshold. Not proof of non-attendance.` : `Below the ${threshold}-person review threshold. Matching counts do not verify attendance.`}</p><form className="reconcile-form" onSubmit={submit}><label htmlFor="claimed-input">Submitted attendance</label><div className="number-input"><input id="claimed-input" type="number" min="0" max={centre.capacity} step="1" required value={claimed} onChange={event => { setClaimed(event.target.value); setSaved(''); setError(''); }} aria-invalid={!valid} /><span>learners</span></div>{!valid && <p className="wf-error">Enter a whole number from 0 to {centre.capacity}.</p>}{error && <p className="wf-error" role="alert">{error}</p>}<button className="button button-primary full-button" disabled={!valid || !dirty} type="submit"><Save size={15} /> Save register update</button><div className={`wf-save-status ${saved && !dirty ? 'is-saved' : ''}`} role="status">{dirty ? 'Unsaved changes' : saved ? <><Check size={13} /> Saved locally at {saved}</> : 'Register up to date'}</div></form></div>;
}
